/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodosnumericoscomputacionales;

import java.awt.Font;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author sajos
 */
public class FrameSeidel extends javax.swing.JInternalFrame {

    List<JTextField> listamatrizA;
    List<JTextField> listavectorB;
    List<JLabel> listaetiquetas;
    List<JTextField> mat1;
    
    List<JTextField> listaMatrizResultante;
    List<JTextField> listavectorResultante;
    List<JLabel> listaigualResultado;
    List <JLabel> listaResultado;
    
    int tamano = 0;

    public FrameSeidel() {
        initComponents();
        
        listamatrizA = new ArrayList<>();
        listavectorB = new ArrayList<>();
        listaetiquetas = new ArrayList<>();

        listaMatrizResultante = new ArrayList();
        listavectorResultante = new ArrayList();
        listaigualResultado = new ArrayList();
        listaResultado = new ArrayList<>();
        ;
        this.setTitle("Gauss Seidel");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlMatrizA = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlB = new javax.swing.JPanel();
        pnlInfo = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        lblingrese = new javax.swing.JLabel();
        txtnovariables = new javax.swing.JTextField();
        btnCrearMatriz = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSolucion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnlIgual = new javax.swing.JPanel();
        scrlX = new javax.swing.JScrollPane();
        pnlAbecedario = new javax.swing.JPanel();
        scrlResultado = new javax.swing.JScrollPane();
        pnlResultado = new javax.swing.JPanel();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1200, 600));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlMatrizA.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(pnlMatrizA);

        pnlB.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane2.setViewportView(pnlB);

        pnlInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbltitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("Gauss Seidel");

        lblingrese.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblingrese.setText("ingrese numero de variables: ");

        btnCrearMatriz.setText("Crear Matriz");
        btnCrearMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMatrizActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSolucion.setText("Solucion");
        btnSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfoLayout.createSequentialGroup()
                                .addComponent(lblingrese, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnovariables))
                            .addGroup(pnlInfoLayout.createSequentialGroup()
                                .addComponent(btnCrearMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo)
                .addGap(18, 18, 18)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblingrese, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnovariables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearMatriz)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSolucion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setBorder(null);

        pnlIgual.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        pnlIgual.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane3.setViewportView(pnlIgual);

        scrlX.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        pnlAbecedario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlAbecedario.setLayout(new java.awt.GridLayout(1, 0));
        scrlX.setViewportView(pnlAbecedario);

        scrlResultado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        pnlResultado.setLayout(new java.awt.GridLayout(1, 0));
        scrlResultado.setViewportView(pnlResultado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrlX)
                            .addComponent(scrlResultado))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(scrlX, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrlResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 252, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMatrizActionPerformed

        pnlMatrizA.removeAll();
        pnlB.removeAll();
        pnlIgual.removeAll();

        listamatrizA.clear();
        listavectorB.clear();
        listaetiquetas.clear();

        try {

            tamano = Integer.parseInt(txtnovariables.getText());

            pnlMatrizA.setLayout(new java.awt.GridLayout(tamano, tamano));
            pnlB.setLayout(new java.awt.GridLayout(tamano, 0));
            pnlIgual.setLayout(new java.awt.GridLayout(tamano, 0));
            for (int i = 0; i < tamano * tamano; i++) {

                creaciontextfield(listamatrizA, pnlMatrizA);

            }
            for (int i = 0; i < tamano; i++) {
                creaciontextfield(listavectorB, pnlB);
                etiquetas(pnlIgual, listaetiquetas);

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Ingrese Solo Numeros", "Error", JOptionPane.ERROR_MESSAGE);
            txtnovariables.setText("");

        }


    }//GEN-LAST:event_btnCrearMatrizActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        pnlMatrizA.removeAll();
        pnlMatrizA.repaint();

        pnlB.removeAll();
        pnlB.repaint();

        pnlIgual.removeAll();
        pnlIgual.repaint();
        
        pnlResultado.removeAll();
        pnlResultado.repaint();
        
        pnlAbecedario.removeAll();
        pnlAbecedario.repaint();
      

        txtnovariables.setText("");


    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolucionActionPerformed

        double [][] MatrizA = null;
        double[] vector = null;
        for (int i = 0; i < listamatrizA.size(); i++) {
            if (listamatrizA.get(i).getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Favor de llenar todos los campos");
                break;

            
            } else {
                listamatrizA.get(i).setEditable(false);
            }

        }
        
        MatrizA = new double[tamano][tamano];
        
        int mA = 0;
        for (int i = 0; i < tamano; i++) {
            for (int j = 0; j < tamano; j++) {
                MatrizA[i][j] = Integer.parseInt(listamatrizA.get(mA).getText());
                mA = mA + 1;
            }
        }
        
        vector = new double[tamano];

        int v = 0;

        for (int i = 0; i < tamano; i++) {
            vector[i] = Double.parseDouble(listavectorB.get(v).getText());
            v = v + 1;

        }     
                

////////////////////////////////////////////////////////////
        
        DecimalFormat DC = new DecimalFormat("#.####");
        
        GaussSeidel solucion = new GaussSeidel(MatrizA, vector);
        double[] x = solucion.solucion(100);
       
        
        
        pnlResultado.removeAll();
        listaResultado.clear();
        pnlAbecedario.removeAll();
        
        List<JLabel> listavariables = new ArrayList<>();
        listavariables.clear();

        pnlResultado.setLayout(new java.awt.GridLayout(0,x.length));
        pnlAbecedario.setLayout(new java.awt.GridLayout(0, x.length));

        char[] abc = Abecedario();
        
            for (int i = 0; i < x.length; i++) {    

                etiquetassolucion(pnlAbecedario,listavariables);
                etiquetassolucion(pnlResultado, listaResultado);
               
                
            }
                        
            int indice3 = 0;
            
            for (int i = 0; i < x.length; i++) {
                
                listavariables.get(i).setText(""+abc[i]);
                listaResultado.get(i).setText(""+x[i]);
               

                indice3 = indice3 + 1;
                
            }
        
    }//GEN-LAST:event_btnSolucionActionPerformed

////////////////////Metodos para poder crear los textFields necesarios segun el usuario los necesite/////////
    public void creaciontextfield(List lista, JPanel panel) {
        Font fuente = new Font("Tahoma", 24, 30);

        JTextField txt = new JTextField();
        txt.setHorizontalAlignment(JTextField.CENTER);
        txt.setFont(fuente);

        txt.setVisible(true);
        txt.setSize(14, 25);
        panel.add(txt);

        panel.validate();
        lista.add(txt);
    }
    
    
//////////////////////////////////////////////////////////////////////////////////////////////////
//metodos para la llenar la matriz identidad y el vector resultante

public void CrearMatriz(double[][] matrizA, int tamano, List<JTextField> listA) {
    
    int mA = 0;
    for (int i = 0; i < tamano; i++) {
        for (int j = 0; j < tamano; j++) {
            matrizA[i][j] = Double.parseDouble(listA.get(mA).getText());
            mA = mA + 1;
        }
    }
    
}

public void CrearVector(double[] vector, int tamano, List<JTextField> lista) {
    
    vector = new double[tamano];
    int v = 0;
    for (int i = 0; i < tamano; i++) {
        vector[i] = Double.parseDouble(lista.get(v).getText());
        v = v + 1;
        
    }
}
    public char[] Abecedario() {
        char[] s;
        s = new char[26];
        for (int i = 0; i < 26; i++) {
            s[i] = (char) ('A' + i);
        }
        return s;
    }
        public void etiquetas(JPanel panel, List lista) {

        Font fuente = new Font("Tahoma", 24, 30);

        JLabel txt = new JLabel();
        txt.setHorizontalAlignment(JTextField.CENTER);
        txt.setFont(fuente);
        txt.setText("=");

        txt.setVisible(true);
        txt.setSize(14, 25);
        panel.add(txt);

        panel.validate();
        lista.add(txt);

    }
    
    public void etiquetassolucion(JPanel panel,List lista) {

        Font fuente = new Font("Tahoma", 6, 15);

        JLabel txt = new JLabel();
        txt.setHorizontalAlignment(JTextField.CENTER);
        txt.setFont(fuente);

        txt.setVisible(true);
        txt.setSize(6, 15);
        panel.add(txt);

        panel.validate();
        lista.add(txt);

    }
///////////////////////////////////////////////////////////////////////////


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearMatriz;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSolucion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblingrese;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel pnlAbecedario;
    private javax.swing.JPanel pnlB;
    private javax.swing.JPanel pnlIgual;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlMatrizA;
    private javax.swing.JPanel pnlResultado;
    private javax.swing.JScrollPane scrlResultado;
    private javax.swing.JScrollPane scrlX;
    private javax.swing.JTextField txtnovariables;
    // End of variables declaration//GEN-END:variables
}
